/**
 * fleet-sim-presets.test.mjs
 * The curated preset file (src/data/fleet_sim_presets.json) is hand-authored:
 * a name plus the base64 the 공유 button produced. check-data-shape only sees
 * the container, so this is where a typo'd blob has to fail — otherwise it
 * renders as a row that loads an empty fleet on the live page.
 *
 * Reads the src/data copy, never public/data: tests run before the build, and
 * the public copy is generated by sync-data.
 */
import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { presetCode, decodeFleetConfig, MAX_FLEETS } from '../../public/js/simulators/fleet-sim.saves.js';

const FILE = new URL('../../src/data/fleet_sim_presets.json', import.meta.url);
const data = JSON.parse(readFileSync(FILE, 'utf8'));

test('the preset file has the shape the page and check-data-shape expect', () => {
    assert.equal(data.version, 1);
    assert.ok(Array.isArray(data.presets), 'presets must be an array');
});

test('every preset carries an id, a name and a decodable fleet', () => {
    const ids = new Set();
    for (const [i, preset] of data.presets.entries()) {
        const where = `presets[${i}]`;
        assert.ok(preset && typeof preset === 'object', `${where}: not an object`);
        assert.ok(preset.id && typeof preset.id === 'string', `${where}: missing id`);
        assert.ok(!ids.has(preset.id), `${where}: duplicate id ${preset.id}`);
        ids.add(preset.id);
        assert.ok(preset.name && typeof preset.name === 'string', `${where}: missing name`);

        const config = decodeFleetConfig(presetCode(preset.code));
        assert.ok(config, `${where}: code does not decode`);
        assert.ok(config.fleets.length <= MAX_FLEETS, `${where}: too many fleets`);
        const ships = config.fleets.reduce((n, f) => n + f.filter(Boolean).length, 0);
        assert.ok(ships >= 1, `${where}: code decodes to an empty fleet`);
    }
});

// ===== presetCode: paste whatever 공유 copied =====

test('presetCode accepts a bare payload and a full share URL alike', () => {
    const bare = 'eyJzIjpbXX0=';
    assert.equal(presetCode(bare), bare);
    assert.equal(presetCode(`https://x.dev/altoy/simulators/fleet-sim/?fleet=${bare}`), bare);
    // 공유 writes the URL through URLSearchParams, which percent-encodes base64's
    // + / and = — a pasted URL therefore arrives escaped.
    assert.equal(presetCode('/fleet-sim/?view=1&fleet=Ya%2Ba%2Fb%3D#top'), 'Ya+a/b=');
    assert.equal(presetCode(null), '');
});

test('a preset URL round-trips through the codec', () => {
    const encoded = 'eyJzIjpbeyJnIjoyMDUxNiwibCI6MTIwLCJhIjoibG92ZSIsImUiOltdfV19';
    const url = `https://x.dev/altoy/simulators/fleet-sim/?fleet=${encodeURIComponent(encoded)}`;
    const config = decodeFleetConfig(presetCode(url));
    assert.equal(config.fleets[0][0].gid, 20516);
});
